# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-10-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerLimit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('upperLimit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixedFee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Isr',
                'verbose_name_plural': 'Isrs',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playSheet', models.IntegerField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=9)),
                ('assimilated', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pantryVouchers', models.DecimalField(decimal_places=2, max_digits=9)),
                ('thirds', models.DecimalField(decimal_places=2, max_digits=9)),
                ('family', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percent', models.IntegerField()),
                ('action', models.SmallIntegerField(choices=[(0, 'CANTIDAD'), (1, 'PORCENTAJE')])),
                ('identifier', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Esquema',
                'verbose_name_plural': 'Esquemas',
            },
        ),
        migrations.CreateModel(
            name='SocialBurdenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet', models.SmallIntegerField(choices=[(1, 'ENFERMEDADES Y MATERNIDAD'), (2, 'INVALIDEZY VIDA'), (3, 'RETIRO'), (4, 'CESANTIA EN EDAD AVANZADA Y VEJEZ'), (5, 'GUARDERIA Y PRESTACIONES SOCIALES'), (6, 'RIESGO DE TRABAJO'), (7, 'APORTACION AL INFONAVIT')])),
                ('percentageEmployee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentageClient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('identifier', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Carga Social',
                'verbose_name_plural': 'Cargas Sociales',
            },
        ),
        migrations.CreateModel(
            name='SubsidoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Subsidio',
                'verbose_name_plural': 'Subsidios',
            },
        ),
    ]
