# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-10-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('enterprise', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apPaterno', models.CharField(max_length=80)),
                ('apMaterno', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('rfc', models.CharField(max_length=15)),
                ('monthlySalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation', models.CharField(max_length=10)),
                ('salaryImss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faults', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creditInfonavit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creditFonacot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alimony', models.DecimalField(decimal_places=2, max_digits=12)),
                ('others', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savingsAccount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicalExpenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stateTax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('socialBurden', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gratification', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paySalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bagToDeal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assimilated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thirdParties', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pantryVouchers', models.DecimalField(decimal_places=2, max_digits=12)),
                ('family', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surplus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('netReceived', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daysPayroll', models.SmallIntegerField()),
                ('identifier', models.IntegerField()),
                ('statusPayroll', models.SmallIntegerField()),
                ('cliente', models.CharField(max_length=15)),
                ('businessRoster', models.CharField(max_length=15)),
                ('businessCash', models.CharField(max_length=15)),
                ('businessAssimilated', models.CharField(max_length=15)),
                ('businessTthirdParties', models.CharField(max_length=15)),
                ('businessPantryVouchers', models.CharField(max_length=15)),
                ('businessFamily', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Nomina Empleado',
                'verbose_name_plural': 'Nomina Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyNoi', models.IntegerField()),
                ('apPaterno', models.CharField(max_length=80)),
                ('apMaterno', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('bankname', models.CharField(blank=True, max_length=255)),
                ('countname', models.IntegerField()),
                ('interbankKey', models.IntegerField()),
                ('dateAntiquity', models.DateField()),
                ('realMonthlySalary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lastDateImss', models.DateField()),
                ('registeredSalary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realSalary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creditInfonavit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creditFonacot', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gratification', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alimony', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gender', models.SmallIntegerField(choices=[(0, 'MASCULINO'), (1, 'FEMENINO')])),
                ('rfc', models.CharField(blank=True, max_length=13, unique=True)),
                ('curp', models.CharField(blank=True, max_length=20)),
                ('domicilie', models.CharField(blank=True, max_length=255)),
                ('workstation', models.CharField(blank=True, max_length=255)),
                ('workday', models.IntegerField()),
                ('timetable', models.CharField(blank=True, max_length=255)),
                ('restday', models.CharField(blank=True, max_length=255)),
                ('calculation', models.SmallIntegerField(choices=[(0, 'BRUTO'), (1, 'NETO'), (2, 'INTEGRO')])),
                ('distribute', models.SmallIntegerField(choices=[(1, 'EFECTIVO'), (2, 'ASIMILADOS'), (3, 'TERCEROS'), (4, 'FAMILIARES')])),
                ('isActive', models.BooleanField(default=True)),
                ('payroll', models.SmallIntegerField(choices=[(1, 'DIARIA'), (7, 'SEMANAL'), (14, 'CATORCENAL'), (15, 'QUINCENAL'), (30, 'MENSUAL')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ClienteModel')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='PaymentEmployeeSchemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePayment', models.SmallIntegerField(choices=[(1, 'NOMINA'), (2, 'EFECTIVO'), (3, 'ASIMILADOS'), (4, 'VALES DE DESPENSA'), (5, 'TERCEROS'), (6, 'FAMILIARES')])),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseModel')),
            ],
            options={
                'verbose_name': 'Empleado Empresa',
                'verbose_name_plural': 'Empleado Empresas',
            },
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='paymentSchema',
            field=models.ManyToManyField(to='employee.PaymentEmployeeSchemaModel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.PaymentSchemeModel'),
        ),
    ]
